### PR TITLE
Feature/wketchum hdflibs time slice

### PR DESCRIPTION
**Pull request by wesketchum**

### CODE REVIEW

**Comment by wesketchum** [comment]
Should only be merged when we also want TimeSlice code merged.

**Comment by wesketchum** [comment]
* One problem here: TimeSliceHeader does not have a way to get the requested components.

**Comment by wesketchum** [comment]
I've just changed the base branch to be `kbiery/df_tp_stream`.

It'd be nice if we can make a draft PR for `biery/df_tp_stream` once this is merged in too, so that we can start to compile further comments (if any) there.

**Review by eflumerf — APPROVED** [review]
LGTM

**Pull request merged**
